import type { ThemeDefinition, ThemeKey } from './types'
import { THEME_KEYS } from './types'

const THEME_DEFINITIONS: Record<ThemeKey, ThemeDefinition> = {
  lavender: {
    key: 'lavender',
    name: { vi: 'Oải hương', en: 'Lavender', zh: '薰衣草', ja: 'ラベンダー' },
    icon: '💜',
    accent: '#8b7be8',
    grad: 'linear-gradient(135deg,#9b86f0,#e089c6)',
    appBg: 'linear-gradient(160deg,#f4eefc,#fbf0f8)',
    mainBg: '#faf6ff',
    panel: '#ffffff',
    text: '#4c4468',
    muted: '#a79fc6',
    border: '#efe8fb',
    borderStrong: '#e6def7',
    chip: '#f4eefc',
    inputBg: '#f8f3ff',
    modalBg: '#ffffff',
    gridLine: '#f1eafb',
    nowLine: '#ff8ec6',
    dark: false,
    sideGrad: 'linear-gradient(175deg,#c7b6f4,#b49bef 58%,#c9a6ea)',
    decor: ['cloud', 'star', 'heart', 'sparkle', 'moon'],
    decorColors: ['#e3d7ff', '#ffd4ea', '#fff0b8', '#dcd0ff'],
  },
  mint: {
    key: 'mint',
    name: { vi: 'Bạc hà', en: 'Matcha', zh: '抹茶', ja: 'まっちゃ' },
    icon: '🍵',
    accent: '#2fb58c',
    grad: 'linear-gradient(135deg,#37bd93,#7bd6a6)',
    appBg: 'linear-gradient(160deg,#ecfaf1,#f2f9e9)',
    mainBg: '#f6fdf8',
    panel: '#ffffff',
    text: '#325247',
    muted: '#9ac2b0',
    border: '#e2f3ea',
    borderStrong: '#d5ecdf',
    chip: '#eef9f1',
    inputBg: '#f2fbf5',
    modalBg: '#ffffff',
    gridLine: '#eaf6ee',
    nowLine: '#ff9a6b',
    dark: false,
    sideGrad: 'linear-gradient(175deg,#8fd8b4,#6cc79a 58%,#a7d98f)',
    decor: ['leaf', 'flower', 'sparkle', 'dot', 'cloud'],
    decorColors: ['#c8f0dc', '#d9f2c4', '#fff0b8', '#bfeee0'],
  },
  strawberry: {
    key: 'strawberry',
    name: { vi: 'Dâu tây', en: 'Strawberry', zh: '草莓', ja: 'いちご' },
    icon: '🍓',
    accent: '#ff6fa5',
    grad: 'linear-gradient(135deg,#ff6fa5,#ff9ec2)',
    appBg: 'linear-gradient(160deg,#fff0f5,#fff2ee)',
    mainBg: '#fff8fa',
    panel: '#ffffff',
    text: '#6e4051',
    muted: '#d69bb2',
    border: '#fbe4ec',
    borderStrong: '#f7d7e2',
    chip: '#fdeef3',
    inputBg: '#fff2f6',
    modalBg: '#ffffff',
    gridLine: '#fbe6ee',
    nowLine: '#ff5d7a',
    dark: false,
    sideGrad: 'linear-gradient(175deg,#ffa6c6,#ff86ac 58%,#ffb3b0)',
    decor: ['flower', 'heart', 'sparkle', 'star', 'dot'],
    decorColors: ['#ffd4e2', '#ffe0ec', '#fff0c0', '#ffd9cf'],
  },
  caramel: {
    key: 'caramel',
    name: { vi: 'Caramel', en: 'Caramel', zh: '焦糖', ja: 'キャラメル' },
    icon: '🧸',
    accent: '#d5904f',
    grad: 'linear-gradient(135deg,#e0a05f,#d98a53)',
    appBg: 'linear-gradient(160deg,#fbf2e6,#fdf4e8)',
    mainBg: '#fdf7ef',
    panel: '#fffdf9',
    text: '#5f4a34',
    muted: '#c3a684',
    border: '#f2e6d3',
    borderStrong: '#ecdcc4',
    chip: '#f8efe0',
    inputBg: '#fbf4e9',
    modalBg: '#fffdf9',
    gridLine: '#f4e9d8',
    nowLine: '#e8724b',
    dark: false,
    sideGrad: 'linear-gradient(175deg,#e6bd8c,#d99e63 58%,#e6b17a)',
    decor: ['star', 'heart', 'sparkle', 'dot', 'cloud'],
    decorColors: ['#f4dcb8', '#ffe6c2', '#f8d0a0', '#ffeccb'],
  },
  ocean: {
    key: 'ocean',
    name: { vi: 'Biển xanh', en: 'Ocean', zh: '海洋', ja: 'うみ' },
    icon: '🐋',
    accent: '#4aa6e8',
    grad: 'linear-gradient(135deg,#4fb0ec,#78c9de)',
    appBg: 'linear-gradient(160deg,#ecf6fd,#eef9fb)',
    mainBg: '#f5fbff',
    panel: '#ffffff',
    text: '#365a70',
    muted: '#96bdd4',
    border: '#e0f0fa',
    borderStrong: '#d2e8f5',
    chip: '#ecf6fd',
    inputBg: '#f1f9fe',
    modalBg: '#ffffff',
    gridLine: '#e8f4fc',
    nowLine: '#ff8ec6',
    dark: false,
    sideGrad: 'linear-gradient(175deg,#9fd3f4,#6fb9ec 58%,#8fd6e0)',
    decor: ['cloud', 'sparkle', 'bubble', 'star', 'dot'],
    decorColors: ['#cfe8fb', '#d6eefb', '#fff2c0', '#c9ecf0'],
  },
  midnight: {
    key: 'midnight',
    name: { vi: 'Đêm sao', en: 'Starry night', zh: '星夜', ja: '星空' },
    icon: '🌙',
    accent: '#9a8bff',
    grad: 'linear-gradient(135deg,#7b7bf0,#b57be0)',
    appBg: '#12132a',
    mainBg: '#161834',
    panel: '#1c1f3d',
    text: '#e9e9fb',
    muted: '#8b8fc0',
    border: 'rgba(255,255,255,.09)',
    borderStrong: 'rgba(255,255,255,.14)',
    chip: 'rgba(255,255,255,.07)',
    inputBg: '#12142e',
    modalBg: '#1c1f3d',
    gridLine: 'rgba(255,255,255,.06)',
    nowLine: '#ff8ec6',
    dark: true,
    sideGrad: 'linear-gradient(175deg,#262c58,#1b1f45 58%,#2c2560)',
    decor: ['star', 'sparkle', 'moon', 'dot', 'heart'],
    decorColors: ['#ffe08a', '#b9a9ff', '#6b6fb0', '#8a7fd8'],
  },
}

export function getThemeDefinition(key: ThemeKey): ThemeDefinition {
  return THEME_DEFINITIONS[key] ?? THEME_DEFINITIONS.lavender
}

export function listThemeDefinitions(): ThemeDefinition[] {
  return THEME_KEYS.map(getThemeDefinition)
}
